version : '3.8'
services:
  db:
    image: postgres:15
    container_name: db-1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - "5433:5432"

  web:
    build: .
    container_name: web-1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      # MATCHED: user=postgres, password=postgres, db=todo_db
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todo_db
    depends_on:
      - db

volumes:
  postgres_data: